### ISSUE TITLE
Not working with Sinystra CConnector

### ISSUE THREAD

**Issue by DoigtdePOULET** [nvb-uy/Death_Knights#3]
Hi! Maybe I'm doing something wrong, but... : 

et.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'death_knights' at 'elocindev.deathknights.DeathKnights'!
	at org.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:81) ~[Connector-1.0.0-beta.46+1.20.1.jar%23385!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.46+1.20.1.jar%23385!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:55) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23389!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.handler$fha000$connectormod$earlyInit(Minecraft.java:24945) ~[client-1.20.1-20230612.114412-srg.jar%23618!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.20.1-20230612.114412-srg.jar%23618!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[forge-47.3.11.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:APP:blinkload-common.mixins.json:client.main.ClientMainMixin from mod blinkload,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'death_knights' at 'elocindev.deathknights.DeathKnights'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:133) ~[Connector-1.0.0-beta.46+1.20.1.jar%23385!/:1.0.0-beta.46+1.20.1] {}
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.46+1.20.1.jar%23385!/:1.0.0-beta.46+1.20.1] {}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:131) ~[Connector-1.0.0-beta.46+1.20.1.jar%23385!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23389!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	... 18 more
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.resources.ResourceLocation elocindev.necronomicon.api.ResourceIdentifier.get(java.lang.String)'
	at elocindev.deathknights.registry.ArmorRegistry.<clinit>(ArmorRegistry.java:101) ~[Death_Knights-0.5.0beta+1.20.1_mapped_srg_1.20.1.jar%231242!/:?] {re:classloading}
	at elocindev.deathknights.config.entries.ArmorConfig.<clinit>(ArmorConfig.java:12) ~[Death_Knights-0.5.0beta+1.20.1_mapped_srg_1.20.1.jar%231242!/:?] {re:classloading}
	at elocindev.deathknights.config.Configs$Items.<clinit>(Configs.java:50) ~[Death_Knights-0.5.0beta+1.20.1_mapped_srg_1.20.1.jar%231242!/:?] {re:classloading}
	at elocindev.deathknights.config.ConfigLoader.init(ConfigLoader.java:27) ~[Death_Knights-0.5.0beta+1.20.1_mapped_srg_1.20.1.jar%231242!/:?] {re:classloading}
	at elocindev.deathknights.DeathKnights.onInitialize(DeathKnights.java:35) ~[Death_Knights-0.5.0beta+1.20.1_mapped_srg_1.20.1.jar%231242!/:?] {re:mixin,re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.46+1.20.1.jar%23385!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23389!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at org.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:81) ~[Connector-1.0.0-beta.46+1.20.1.jar%23385!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.46+1.20.1.jar%23385!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:55) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23389!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.handler$fha000$connectormod$earlyInit(Minecraft.java:24945) ~[client-1.20.1-20230612.114412-srg.jar%23618!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.20.1-20230612.114412-srg.jar%23618!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}

**Comment by nebulazorua** [comment]
I believe its related to the versioning not being semver-compliant (it should be 0.5.0-beta afaik)

**Comment by MarkTheRustyShovel** [comment]
This actually does work with Synstra connector, but only if you have trinkets. Which is clearly not intended behavior.

**Comment by PraiseTheSeune** [comment]
> This actually does work with Synstra connector, for me. It's possible you didn't install trinkets, which is a dependency for Spell Engine, but for some reason the others don't crash without it.

I have the exact same problem even with Trinckets. Could it be possible to see your mod list? (for mine everything is up to date)

**Comment by MarkTheRustyShovel** [comment]
honestly i already forgot my modlist because ive doing some experimenting.

there's a bigger issue with missing texture/models on a lot of spell engine
mods when using sinytra

**Comment by nvb-uy** [comment]
Please report to the Connector developer
